### ISSUE TITLE
csvapi-front using hardcoded link to gouvfr csvapi

### ISSUE THREAD

**Issue by mayjolux** [opendatateam/udata-tabular-preview#7]
I successfully deployed the udata-tabular-preview and I can also click on the "Previsualize" button of a csv-resource, but despite having specified our csvapi url in the udata.cfg, it still uses the gouvfr csvapi link when using csvapi-front the default UI displaying preview. If I specify the dataexplorer UI it seems to work, is there any significant difference between the csvapi-front and dataexplorer?

Thanks in advance for any clarification!

**Comment by abulte** [comment]
It's probably because the build time configuration of `csvapi-front` takes precedence over the runtime one https://github.com/opendatateam/csvapi-front/blob/master/src/config.js#L16.

You can try to remove the `VUE_APP_CSVAPI_URL` variable when building `csvapi-front` https://github.com/opendatateam/csvapi-front#environment-variables.

**Comment by mayjolux** [comment]
Okay thanks for the info, I will give it a try!

**Comment by abulte** [comment]
You're welcome, please reopen the issue if it does not fix the problem.
